# fly.toml app configuration file generated for catargo on 2026-04-26T10:03:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'catargo'
primary_region = 'sjc'
swap_size_mb = 512

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
